'use client';

import { useEffect, useState } from 'react';

const blank = { name: '', email: '', password: '', role: 'admin' };
export default function UsersPage() {
  const [users, setUsers] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [message, setMessage] = useState('');
  const load = () => fetch('/api/admin/users').then((response) => response.json()).then(setUsers); useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); const response = await fetch(editing ? `/api/admin/users/${editing}` : '/api/admin/users', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); setMessage(response.ok ? 'Admin saved.' : result.error || 'Unable to save admin'); if (response.ok) { setForm(blank); setEditing(null); load(); } };
  const remove = async (id) => { if (confirm('Delete this administrator?')) { await fetch(`/api/admin/users/${id}`, { method: 'DELETE' }); load(); } };
  return <div className="max-w-5xl space-y-6"><div><h1 className="text-white text-2xl font-bold">Admin users</h1><p className="text-white/35 text-sm mt-1">Only owners can create, edit, or remove administrator accounts.</p></div><form onSubmit={save} className="bg-[#1a1a1a] border border-white/5 rounded-2xl p-5 grid grid-cols-1 sm:grid-cols-5 gap-3"><input required placeholder="Name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="input-dark" /><input required={!editing} type="email" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="input-dark" /><input required={!editing} type="password" placeholder={editing ? 'New password (optional)' : 'Temporary password'} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="input-dark" /><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} className="input-dark"><option value="admin">Admin</option><option value="editor">Editor</option></select><button className="bg-white text-black rounded-xl px-4 py-2 text-sm font-bold">{editing ? 'Save admin' : 'Add admin'}</button><p className="text-emerald-400 text-sm sm:col-span-5">{message}</p></form><div className="bg-[#1a1a1a] border border-white/5 rounded-2xl p-5">{users.map((user) => <div key={user._id} className="flex flex-wrap gap-3 items-center justify-between border-b border-white/5 py-3 last:border-0"><div><p className="text-white">{user.name}</p><p className="text-white/35 text-xs">{user.email}</p></div><div className="flex items-center"><span className="text-white/50 text-xs uppercase mr-5">{user.role}</span><button onClick={() => { setEditing(user._id); setForm({ name: user.name, email: user.email, password: '', role: user.role }); }} className="text-white/60 mr-4">Edit</button><button onClick={() => remove(user._id)} className="text-red-400/70">Delete</button></div></div>)}{users.length === 0 && <p className="text-white/25 text-sm">No administrators found.</p>}</div></div>;
}